.catalog:
  name: "jenkins-erlang"
  version: "v0.0.1"
  description: "jenkins with erlang base."
  minimum_rancher_version: v1.0.0
  questions:
    - variable: jenkins_port
      description: "Public port for access to Jenkins"
      label: "Jenkins Public Port"
      required: true
      default: 8080
      type: "int"
    - variable: jenkins_dir
      description: "Jenkins Home Dir "
      label: "Jenkins Home Dir"
      required: true
      default: /data/jenkins
      type: "string"


version: '2'
services:
  jenkins:
    scale: 1
    start_on_create: true
  jenkins-data:
    scale: 1
    start_on_create: true